services:
  - type: web
    name: transcript-formatter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true